data_model:
  name: LOGAN v3.0 Core Data Model
  version: "3.0"
  description: Hierarchical tagged key-value structure with strict typing and immutability controls
  structure:
    root:
      type: map
      required: true
      children:
        - key: subject-un
          type: string
          immutable: true
          example: "glitched-ai-entity"
        - key: intent-un
          type: string
          values:
            - explain-im
            - generate-im
            - calculate-im
            - render-im
          required: true
        - key: appearance-op
          type: list[map]
          optional: true
        - key: system-sys
          type: map
          purpose: runtime constraints
        - key: override-cx
          type: map
          purpose: hot-patch system-sys
          priority: highest
        - key: action-un
          type: list[map]
          required: true
        - key: context-op
          type: map
          optional: true
  tagging_conventions:
    suffix_meaning:
      -un: unit / immutable identifier
      -im: immutable value
      -ex: exact / literal
      -ta: targeted / parameterized
      -op: optional block
      -cx: context / override
  override_resolution: last override wins (override-cx > system-sys > defaults)
  validation_mode: loose (as overridden)